using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Projectile : MonoBehaviour
{
    [SerializeField]private float lifeTime = 1f;
    private float damage;
    private float timer;
    // Start is called before the first frame update
    void Start()
    {
        timer = 0;
    }

    // Update is called once per frame
    void Update()
    {
        timer += Time.deltaTime;
        if(timer >= lifeTime){
            Destroy(gameObject);
        }
    }

    public void SetDamage(float dmg){
        this.damage = dmg;
    }

    public float GetDamage(){
        return damage;
    }
}
